version: "3.3"

services:
  app:
    image: nest-boilerplate
    build: .
    entrypoint: ["dockerize", "-wait", "tcp://db:5432", "-timeout", "25s"]
    command: ["node", "dist/main"]
    ports:
      - 3000:3000
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=nest-boilerplate
    depends_on:
      - db
  db:
    image: postgres:13.0
    container_name: nest-boilerplate-db
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nest-boilerplate
