version: "3.3"

services:
  db:
    image: postgres:13.0
    container_name: nest-boilerplate-db
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nest_boilerplate
